baseURL = "https://www.farshid.ws/"
languageCode = "en-us"
title = "Farshid Tavakolizadeh"
theme="archie"
copyright = "© Farshid Tavakolizadeh"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
ignoreErrors = ["error-remote-getjson"] # to ignore instagram resource fetch error

[markup.goldmark.renderer]
	unsafe= true

[params]
	mode="light" # light/dark/auto
	useCDN=true
	#subtitle = "Can add markdown here."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/farshidtz"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/farshidt"

[[params.social]]
name = "Google Scholar"
icon = "book-open"
url = "https://scholar.google.com/citations?user=RULta1sAAAAJ&hl=en"

#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1

#[[menu.main]]
#name = "Posts"
#url = "/posts"
#weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4
